Upgraded to build in VS2015. Fixed build error CS1906 - commas in resource file names (test project). Removed packages from git ignore so nuget packages do not require restore following clone. Removed legacy Backup folder